#!/bin/sh

sudo apt-get -y install git build-essential libgtk2.0-dev libwxgtk2.8-dev libwx-perl libmodule-build-perl libnet-dbus-perl libexpat1-dev	
sudo apt-get -y install cpanminus libxmu-dev freeglut3-dev
sudo apt-get -y install curl
curl -L http://cpanmin.us | perl - --sudo App::cpanminus
sudo apt-get -y install libwx-perl
sudo cpanm Boost::Geometry::Utils Math::Clipper Math::ConvexHull Math::ConvexHull::MonotoneChain Math::Geometry::Voronoi Math::PlanePath Moo Wx
sudo usermod -a -G dialout $LOGNAME
sudo apt-get -y install mono-devel
sudo apt-get -y install libmono-system-serviceprocess4.0-cil libmono-winforms2.0-cil
# Newer linux distros need this now to get all libraries
sudo apt-get -y install mono-reference-assemblies-2.0 mono-devel
#cd Slic3r
#sudo perl Build.PL
#sudo perl Build.PL --gui
#cd ..
